# Funding sources for did-stellar
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom: ['https://communityfund.stellar.org/submissions/recUBbVLf5Vj8oEW0']
